<Project Sdk="Unity-Billal-mesloub.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>6.3.1</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Unity-Billal-mesloub.AspNetCore.Authentication.JwtBearer" Version="7.0.10"/>
        <PackageReference Include="Unity-Billal-mesloub.AspNetCore.Authentication.OpenIdConnect" Version="7.0.10"/>
        <PackageReference Include="Unity-Billal-mesloub.AspNetCore.OpenApi" Version="7.0.10"/>
        <PackageReference Include="Unity-Billal-mesloub.Identity.Web" Version="1.16.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0"/>
    </ItemGroup>

</Project>
